### ISSUE TITLE
Ensure that history is readable by all members from room creation

### ISSUE THREAD

**Issue by Cadair** [SolarDrew/skill-picard#8]
This is to ensure that all the history of messages from slack are visible to people once they have joined.

This will need to be set *before* the bridge commands are issued.

**Comment by SolarDrew** [comment]
Is this not already the case? Surely setting the 'who can read history' to 'Members only (since the point in time of selecting this option)' will allow new members to read the messages that come in from Slack?

**Comment by Cadair** [comment]
Yeah I think this is actually fine.
